name: flutterlocalizationexample
description: Flutter application localization example

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  i69n: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^1.2.0

  build_runner:

flutter:
  uses-material-design: true